// <auto-generated />
namespace PersonalAccounting.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initial14000129 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial14000129));
        
        string IMigrationMetadata.Id
        {
            get { return "202104180707541_initial-14000129"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
